-- ========================================================
-- Supabase Database Schema & Migration Script for Civil Dept
-- ========================================================

-- 1. NOTICES TABLE
CREATE TABLE IF NOT EXISTS public.notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    date TEXT,
    website_link TEXT,
    picture_link TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.notices ADD COLUMN IF NOT EXISTS date TEXT;
ALTER TABLE public.notices ADD COLUMN IF NOT EXISTS website_link TEXT;
ALTER TABLE public.notices ADD COLUMN IF NOT EXISTS picture_link TEXT;

-- Enable RLS & set access policies for notices
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public select on notices" ON public.notices;
CREATE POLICY "Allow public select on notices" ON public.notices FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert on notices" ON public.notices;
CREATE POLICY "Allow public insert on notices" ON public.notices FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public delete on notices" ON public.notices;
CREATE POLICY "Allow public delete on notices" ON public.notices FOR DELETE USING (true);


-- 2. EVENTS TABLE
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    date TEXT,
    venue TEXT,
    time TEXT,
    website_link TEXT,
    picture_link TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.events ADD COLUMN IF NOT EXISTS date TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS venue TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS time TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS website_link TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS picture_link TEXT;

-- Enable RLS & set access policies for events
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public select on events" ON public.events;
CREATE POLICY "Allow public select on events" ON public.events FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert on events" ON public.events;
CREATE POLICY "Allow public insert on events" ON public.events FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public delete on events" ON public.events;
CREATE POLICY "Allow public delete on events" ON public.events FOR DELETE USING (true);


-- 3. FACULTY TABLE
CREATE TABLE IF NOT EXISTS public.faculty (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    designation TEXT DEFAULT 'Assistant Professor',
    qualification TEXT,
    specialization TEXT,
    experience TEXT,
    email TEXT,
    website_link TEXT,
    picture_link TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.faculty ADD COLUMN IF NOT EXISTS website_link TEXT;
ALTER TABLE public.faculty ADD COLUMN IF NOT EXISTS picture_link TEXT;

-- Enable RLS & set access policies for faculty
ALTER TABLE public.faculty ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public select on faculty" ON public.faculty;
CREATE POLICY "Allow public select on faculty" ON public.faculty FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert on faculty" ON public.faculty;
CREATE POLICY "Allow public insert on faculty" ON public.faculty FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public delete on faculty" ON public.faculty;
CREATE POLICY "Allow public delete on faculty" ON public.faculty FOR DELETE USING (true);
